# Generated by Django 5.0.2 on 2024-07-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionalert',
            name='image_path',
        ),
        migrations.AddField(
            model_name='motionalert',
            name='image',
            field=models.BinaryField(default=b''),
        ),
    ]
